version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: container
    tty: true
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./docker/mysql:/var/lib/mysql/
